version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: circleci/mongo:3.4.4

    working_directory: ~/tdd-fs-devs

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test